//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace NotiOfima.Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class NotiOfimaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto NotiOfimaEntities usando la cadena de conexión encontrada en la sección 'NotiOfimaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public NotiOfimaEntities() : base("name=NotiOfimaEntities", "NotiOfimaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto NotiOfimaEntities.
        /// </summary>
        public NotiOfimaEntities(string connectionString) : base(connectionString, "NotiOfimaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto NotiOfimaEntities.
        /// </summary>
        public NotiOfimaEntities(EntityConnection connection) : base(connection, "NotiOfimaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<NotiOfimaDatos> NotiOfimaDatos
        {
            get
            {
                if ((_NotiOfimaDatos == null))
                {
                    _NotiOfimaDatos = base.CreateObjectSet<NotiOfimaDatos>("NotiOfimaDatos");
                }
                return _NotiOfimaDatos;
            }
        }
        private ObjectSet<NotiOfimaDatos> _NotiOfimaDatos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<NotiOfimaConfiguracion> NotiOfimaConfiguracions
        {
            get
            {
                if ((_NotiOfimaConfiguracions == null))
                {
                    _NotiOfimaConfiguracions = base.CreateObjectSet<NotiOfimaConfiguracion>("NotiOfimaConfiguracions");
                }
                return _NotiOfimaConfiguracions;
            }
        }
        private ObjectSet<NotiOfimaConfiguracion> _NotiOfimaConfiguracions;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MTPAI> MTPAIS
        {
            get
            {
                if ((_MTPAIS == null))
                {
                    _MTPAIS = base.CreateObjectSet<MTPAI>("MTPAIS");
                }
                return _MTPAIS;
            }
        }
        private ObjectSet<MTPAI> _MTPAIS;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet NotiOfimaDatos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNotiOfimaDatos(NotiOfimaDatos notiOfimaDatos)
        {
            base.AddObject("NotiOfimaDatos", notiOfimaDatos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet NotiOfimaConfiguracions. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNotiOfimaConfiguracions(NotiOfimaConfiguracion notiOfimaConfiguracion)
        {
            base.AddObject("NotiOfimaConfiguracions", notiOfimaConfiguracion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MTPAIS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMTPAIS(MTPAI mTPAI)
        {
            base.AddObject("MTPAIS", mTPAI);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NotiOfimaModel", Name="MTPAI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MTPAI : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MTPAI.
        /// </summary>
        /// <param name="cODIGO">Valor inicial de la propiedad CODIGO.</param>
        public static MTPAI CreateMTPAI(global::System.String cODIGO)
        {
            MTPAI mTPAI = new MTPAI();
            mTPAI.CODIGO = cODIGO;
            return mTPAI;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODIGO
        {
            get
            {
                return _CODIGO;
            }
            set
            {
                if (_CODIGO != value)
                {
                    OnCODIGOChanging(value);
                    ReportPropertyChanging("CODIGO");
                    _CODIGO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CODIGO");
                    OnCODIGOChanged();
                }
            }
        }
        private global::System.String _CODIGO;
        partial void OnCODIGOChanging(global::System.String value);
        partial void OnCODIGOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCIO
        {
            get
            {
                return _DESCRIPCIO;
            }
            set
            {
                OnDESCRIPCIOChanging(value);
                ReportPropertyChanging("DESCRIPCIO");
                _DESCRIPCIO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCIO");
                OnDESCRIPCIOChanged();
            }
        }
        private global::System.String _DESCRIPCIO;
        partial void OnDESCRIPCIOChanging(global::System.String value);
        partial void OnDESCRIPCIOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NotiOfimaModel", Name="NotiOfimaConfiguracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NotiOfimaConfiguracion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto NotiOfimaConfiguracion.
        /// </summary>
        /// <param name="frecuenciaMostrar">Valor inicial de la propiedad FrecuenciaMostrar.</param>
        /// <param name="ultimaEjecucion">Valor inicial de la propiedad UltimaEjecucion.</param>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tiempoInactivo">Valor inicial de la propiedad tiempoInactivo.</param>
        public static NotiOfimaConfiguracion CreateNotiOfimaConfiguracion(global::System.Int32 frecuenciaMostrar, global::System.DateTime ultimaEjecucion, global::System.Guid id, global::System.Int32 tiempoInactivo)
        {
            NotiOfimaConfiguracion notiOfimaConfiguracion = new NotiOfimaConfiguracion();
            notiOfimaConfiguracion.FrecuenciaMostrar = frecuenciaMostrar;
            notiOfimaConfiguracion.UltimaEjecucion = ultimaEjecucion;
            notiOfimaConfiguracion.id = id;
            notiOfimaConfiguracion.tiempoInactivo = tiempoInactivo;
            return notiOfimaConfiguracion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FrecuenciaMostrar
        {
            get
            {
                return _FrecuenciaMostrar;
            }
            set
            {
                OnFrecuenciaMostrarChanging(value);
                ReportPropertyChanging("FrecuenciaMostrar");
                _FrecuenciaMostrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrecuenciaMostrar");
                OnFrecuenciaMostrarChanged();
            }
        }
        private global::System.Int32 _FrecuenciaMostrar;
        partial void OnFrecuenciaMostrarChanging(global::System.Int32 value);
        partial void OnFrecuenciaMostrarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UltimaEjecucion
        {
            get
            {
                return _UltimaEjecucion;
            }
            set
            {
                OnUltimaEjecucionChanging(value);
                ReportPropertyChanging("UltimaEjecucion");
                _UltimaEjecucion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UltimaEjecucion");
                OnUltimaEjecucionChanged();
            }
        }
        private global::System.DateTime _UltimaEjecucion;
        partial void OnUltimaEjecucionChanging(global::System.DateTime value);
        partial void OnUltimaEjecucionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tiempoInactivo
        {
            get
            {
                return _tiempoInactivo;
            }
            set
            {
                OntiempoInactivoChanging(value);
                ReportPropertyChanging("tiempoInactivo");
                _tiempoInactivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tiempoInactivo");
                OntiempoInactivoChanged();
            }
        }
        private global::System.Int32 _tiempoInactivo;
        partial void OntiempoInactivoChanging(global::System.Int32 value);
        partial void OntiempoInactivoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NotiOfimaModel", Name="NotiOfimaDatos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NotiOfimaDatos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto NotiOfimaDatos.
        /// </summary>
        /// <param name="cantidadMostrar">Valor inicial de la propiedad CantidadMostrar.</param>
        /// <param name="fechaExpiracion">Valor inicial de la propiedad FechaExpiracion.</param>
        /// <param name="frecuenciaMostrar">Valor inicial de la propiedad FrecuenciaMostrar.</param>
        /// <param name="idNota">Valor inicial de la propiedad idNota.</param>
        /// <param name="link">Valor inicial de la propiedad Link.</param>
        /// <param name="titulo">Valor inicial de la propiedad Titulo.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad FechaCreacion.</param>
        /// <param name="codigoPais">Valor inicial de la propiedad CodigoPais.</param>
        public static NotiOfimaDatos CreateNotiOfimaDatos(global::System.Int32 cantidadMostrar, global::System.DateTime fechaExpiracion, global::System.Decimal frecuenciaMostrar, global::System.Guid idNota, global::System.String link, global::System.String titulo, global::System.DateTime fechaCreacion, global::System.String codigoPais)
        {
            NotiOfimaDatos notiOfimaDatos = new NotiOfimaDatos();
            notiOfimaDatos.CantidadMostrar = cantidadMostrar;
            notiOfimaDatos.FechaExpiracion = fechaExpiracion;
            notiOfimaDatos.FrecuenciaMostrar = frecuenciaMostrar;
            notiOfimaDatos.idNota = idNota;
            notiOfimaDatos.Link = link;
            notiOfimaDatos.Titulo = titulo;
            notiOfimaDatos.FechaCreacion = fechaCreacion;
            notiOfimaDatos.CodigoPais = codigoPais;
            return notiOfimaDatos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantidadMostrar
        {
            get
            {
                return _CantidadMostrar;
            }
            set
            {
                OnCantidadMostrarChanging(value);
                ReportPropertyChanging("CantidadMostrar");
                _CantidadMostrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadMostrar");
                OnCantidadMostrarChanged();
            }
        }
        private global::System.Int32 _CantidadMostrar;
        partial void OnCantidadMostrarChanging(global::System.Int32 value);
        partial void OnCantidadMostrarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaExpiracion
        {
            get
            {
                return _FechaExpiracion;
            }
            set
            {
                OnFechaExpiracionChanging(value);
                ReportPropertyChanging("FechaExpiracion");
                _FechaExpiracion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaExpiracion");
                OnFechaExpiracionChanged();
            }
        }
        private global::System.DateTime _FechaExpiracion;
        partial void OnFechaExpiracionChanging(global::System.DateTime value);
        partial void OnFechaExpiracionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FrecuenciaMostrar
        {
            get
            {
                return _FrecuenciaMostrar;
            }
            set
            {
                OnFrecuenciaMostrarChanging(value);
                ReportPropertyChanging("FrecuenciaMostrar");
                _FrecuenciaMostrar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrecuenciaMostrar");
                OnFrecuenciaMostrarChanged();
            }
        }
        private global::System.Decimal _FrecuenciaMostrar;
        partial void OnFrecuenciaMostrarChanging(global::System.Decimal value);
        partial void OnFrecuenciaMostrarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid idNota
        {
            get
            {
                return _idNota;
            }
            set
            {
                if (_idNota != value)
                {
                    OnidNotaChanging(value);
                    ReportPropertyChanging("idNota");
                    _idNota = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idNota");
                    OnidNotaChanged();
                }
            }
        }
        private global::System.Guid _idNota;
        partial void OnidNotaChanging(global::System.Guid value);
        partial void OnidNotaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Imagen
        {
            get
            {
                return StructuralObject.GetValidValue(_Imagen);
            }
            set
            {
                OnImagenChanging(value);
                ReportPropertyChanging("Imagen");
                _Imagen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Imagen");
                OnImagenChanged();
            }
        }
        private global::System.Byte[] _Imagen;
        partial void OnImagenChanging(global::System.Byte[] value);
        partial void OnImagenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodigoPais
        {
            get
            {
                return _CodigoPais;
            }
            set
            {
                OnCodigoPaisChanging(value);
                ReportPropertyChanging("CodigoPais");
                _CodigoPais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodigoPais");
                OnCodigoPaisChanged();
            }
        }
        private global::System.String _CodigoPais;
        partial void OnCodigoPaisChanging(global::System.String value);
        partial void OnCodigoPaisChanged();

        #endregion

    
    }

    #endregion

    
}
