//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotiOfima.Visualizador.NotiOfimaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotiOfimaService.IServiceNotiOfima")]
    public interface IServiceNotiOfima {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNotiOfima/consultarNotas", ReplyAction="http://tempuri.org/IServiceNotiOfima/consultarNotasResponse")]
        NotiOfima.Entidades.Model.NotiOfimaTable[] consultarNotas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNotiOfima/consultarFrecuenciaMostrar", ReplyAction="http://tempuri.org/IServiceNotiOfima/consultarFrecuenciaMostrarResponse")]
        int consultarFrecuenciaMostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNotiOfima/consultarTiempoInactivo", ReplyAction="http://tempuri.org/IServiceNotiOfima/consultarTiempoInactivoResponse")]
        int consultarTiempoInactivo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNotiOfimaChannel : NotiOfima.Visualizador.NotiOfimaService.IServiceNotiOfima, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNotiOfimaClient : System.ServiceModel.ClientBase<NotiOfima.Visualizador.NotiOfimaService.IServiceNotiOfima>, NotiOfima.Visualizador.NotiOfimaService.IServiceNotiOfima {
        
        public ServiceNotiOfimaClient() {
        }
        
        public ServiceNotiOfimaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNotiOfimaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotiOfimaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotiOfimaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NotiOfima.Entidades.Model.NotiOfimaTable[] consultarNotas() {
            return base.Channel.consultarNotas();
        }
        
        public int consultarFrecuenciaMostrar() {
            return base.Channel.consultarFrecuenciaMostrar();
        }
        
        public int consultarTiempoInactivo() {
            return base.Channel.consultarTiempoInactivo();
        }
    }
}
